name: future_shopping2
description: Smart Shopping App with BLE beacon detection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  flutter_blue_plus: ^1.31.7
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2
  # Additional dependencies for enhanced functionality
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.0
  uuid: ^4.2.1
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
