// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULj3FzGspJTjdXpuZ4TkJyeR387dNl0A',
    appId: '1:1016284993833:web:4ea6c07d79bd5818cc7f38',
    messagingSenderId: '1016284993833',
    projectId: 'smart-shopping-app-5177b',
    authDomain: 'smart-shopping-app-5177b.firebaseapp.com',
    storageBucket: 'smart-shopping-app-5177b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULj3FzGspJTjdXpuZ4TkJyeR387dNl0A',
    appId: '1:1016284993833:android:4ea6c07d79bd5818cc7f38',
    messagingSenderId: '1016284993833',
    projectId: 'smart-shopping-app-5177b',
    storageBucket: 'smart-shopping-app-5177b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULj3FzGspJTjdXpuZ4TkJyeR387dNl0A',
    appId: '1:1016284993833:ios:4ea6c07d79bd5818cc7f38',
    messagingSenderId: '1016284993833',
    projectId: 'smart-shopping-app-5177b',
    storageBucket: 'smart-shopping-app-5177b.firebasestorage.app',
    iosClientId: '1016284993833-example.apps.googleusercontent.com',
    iosBundleId: 'com.example.futureshopping2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULj3FzGspJTjdXpuZ4TkJyeR387dNl0A',
    appId: '1:1016284993833:ios:4ea6c07d79bd5818cc7f38',
    messagingSenderId: '1016284993833',
    projectId: 'smart-shopping-app-5177b',
    storageBucket: 'smart-shopping-app-5177b.firebasestorage.app',
    iosClientId: '1016284993833-example.apps.googleusercontent.com',
    iosBundleId: 'com.example.futureshopping2',
  );
}
